package book;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Set;

public class ChangeMessage {
    public static String ReaderName;
    public static String LoginPassword;
    public static int SaveStatus;
    public static String LoginToken;
    public static long expirationTime;
    public static String photo;
    public static String nickname;
    public static List<String> borrow;
    public static List<String> returnBack;
    public static int position;
    public void saada()
   {
      int a=1;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
      a++;
   }
}
class BookMessage {
    public static String RName;
    public static String Logword;
    public static int Saveus;
    public static String Loen;
    public static long expinTime;
    public static String pto;
    public static String nicame;
    public static List<String> bow;
    public static List<String> retck;
    public static int poson;
}
class Booke {
    public static String RNme;
    public static String Loword;
    public static int Saves;
    public static String Lon;
    public static long expiTime;
    public static String po;
    public static String nicae; 
}
class BoMessage {
    public static String RNam;
    public static String Logwor;
    public static int Saveu;
    public static String Loe;
    public static long expinTim;
    public static String pt;
    public static String nie;
    public static List<String> bw;
    public static List<String> retk;
    public static int posn;
}
